export type Pokemon = {
    abilities: object,
    base_experience: number,
    cries: object,
    forms: object,
    game_indices: object,
    height: number,
    held_items: object,
    id: number,
    is_default: true,
    location_area_encounters: string,
    moves: object,
    name: string,
    order: number,
    past_abilities: object,
    past_types: object,
    species: object,
    sprites: object,
    stats: object,
    types: object,
    weight: number,
};